export const ROLES = {
  ADMIN:'AD',
  CUBICULOS:'CU',
  BIBLIOTECA:'BI',
  RECURSOS_ELECTRONICOS:'RE',
  CUBICULOS_USUARIOS:'CU_US',
  BIBLIOTECA_USUARIOS:'BI_US',
  RECURSOS_ELECTRONICOS_USUARIOS:'RE_US',
}
